### ISSUE TITLE
Docker Image Build Fails (Not in gzip format)

### ISSUE THREAD

**Issue by djhejna** [data-science-on-aws/workshop#12]
!docker build -t $docker_repo:$docker_tag -f container/Dockerfile ./container

Step 14/33 : RUN curl -sL --retry 3   "http://archive.apache.org/dist/hadoop/common/hadoop-$HADOOP_VERSION/hadoop-$HADOOP_VERSION.tar.gz"   | gunzip   | tar -x -C /usr/  && rm -rf $HADOOP_HOME/share/doc  && chown -R root:root $HADOOP_HOME
 ---> Running in 31faa5c5bfe7

gzip: stdin: not in gzip format
tar: This does not look like a tar archive
tar: Exiting with failure status due to previous errors
The command '/bin/sh -c curl -sL --retry 3   "http://archive.apache.org/dist/hadoop/common/hadoop-$HADOOP_VERSION/hadoop-$HADOOP_VERSION.tar.gz"   | gunzip   | tar -x -C /usr/  && rm -rf $HADOOP_HOME/share/doc  && chown -R root:root $HADOOP_HOME' returned a non-zero code: 2

**Comment by cfregly** [comment]
possible throttling issue when pulling from archive.apache.org.

can you try again and let me know?  we will need to add retries - or burn the .tar.gz into the Docker image and snip the remote dependency.

**Comment by cfregly** [comment]
for now, i added more retries on the curl.  in the long term, we'll address this with https://github.com/data-science-on-aws/workshop/issues/24

**Comment by cfregly** [comment]
fixed here:  https://github.com/data-science-on-aws/workshop/issues/24
