### ISSUE TITLE
TrainingInput import from sagemaker.inputs doesn't work everytime

### ISSUE THREAD

**Issue by Shubhamsaboo** [data-science-on-aws/workshop#123]
Few times restarting the notebook fixed it for me, but I am not sure of the root cause of the error.  Can you please look into it and figure out what's causing the problem?

**Comment by cfregly** [comment]
You’re likely switching between SageMaker SDK 1.x and 2.x

Can you do a pip list and verify?  The latest code only works with SageMaker SDK 2.x

**Comment by Shubhamsaboo** [comment]
Got it @cfregly , Thanks!!
