### ISSUE TITLE
no stored variable or alias autopilot_endpoint_name

### ISSUE THREAD

**Issue by snairINA** [data-science-on-aws/workshop#126]
![Capture](https://user-images.githubusercontent.com/72281037/95036114-f4633180-0694-11eb-8fcd-62255c46ad52.PNG)
getting this error while executing from the notebook

**Comment by antje** [comment]
Hi, 

the preceding notebook (https://github.com/data-science-on-aws/workshop/blob/master/02_automl/02_Train_Reviews_Autopilot.ipynb) deploys the trained Autopilot model as an endpoint and sets this variable. Can you verify that 02_Train_Reviews_Autopilot.ipynb notebook has succesfully completed? 

You can find the relevant code at the end of 02_Train_Reviews_Autopilot.ipynb: 

![image](https://user-images.githubusercontent.com/23338582/95444865-9a958c80-095e-11eb-9047-fd75d9d08e38.png)

**Comment by snairINA** [comment]
Antje,
   It did work, you are right, I did not run the 02_Train_Reviews_Autopilot.ipynb notebook. Appreciate your help.

V/R
Suresh Nair / President & CEO
Mobile #:  (703)786-7047
Fax #:  (571)295-4183
INA Solutions Inc
161 Fort Evans Rd NE, Suite 210, Leesburg, VA 20176
www.ina-solutions.com<http://www.ina-solutions.com/>
SBA 8A Certified| HUBZone Certified| GSA IT 70| ISO 9001-2015| CMMI DEV /3

This e-mail message may contain confidential or legally privileged information and is intended only for the use of the intended recipient(s). Any unauthorized disclosure, dissemination, distribution, copying or the taking of any action in reliance on the information herein is prohibited. E-mails are not secure and cannot be guaranteed to be error free as they can be intercepted, amended, or contain viruses. Anyone who communicates with us by e-mail is deemed to have accepted these risks. INA is not responsible for errors or omissions in this message and denies any responsibility for any damage arising from the use of e-mail. Any opinion and other statement contained in this message and any attachment are solely those of the author and do not necessarily represent those of the company.

**Comment by snairINA** [comment]
Can i increase the accuracy by increasing the candidates from 3 to 5?

V/R
Suresh Nair / President & CEO
Mobile #: (703)786-7047
Fax #: (571)295-4183
INA Solutions Inc
161 Fort Evans Rd NE, Suite 210, Leesburg, VA 20176
www.ina-solutions.com

SBA 8A Certified| HUBZone Certified| GSA IT 70| ISO 9001-2015| CMMI DEV /3

This e-mail message may contain confidential or legally privileged information and is intended only for the use of the intended recipient(s). Any unauthorized disclosure, dissemination, distribution, copying or the taking of any action in reliance on the information herein is prohibited. E-mails are not secure and cannot be guaranteed to be error free as they can be intercepted, amended, or contain viruses. Anyone who communicates with us by e-mail is deemed to have accepted these risks. INA is not responsible for errors or omissions in this message and denies any responsibility for any damage arising from the use of e-mail. Any opinion and other statement contained in this message and any attachment are solely those of the author and do not necessarily represent those of the company.

________________________________

**Comment by antje** [comment]
Accuracy depends on many factors such as dataset, size of training data, combination of data pre-processing and algorithm, training and tuning time etc. An increased number of model candidates will try out different combinations of data pre-processing and algorithms, hence is only addressing one part. I would certainly increase the size of training data as well to achieve higher accuracy.
