### ISSUE TITLE
notebook server issue

### ISSUE THREAD

**Issue by radhakrishnang** [data-science-on-aws/workshop#131]
When scaling down the nodes to 1 and then scaling up to 5 i am getting issue with notebook server 
![image](https://user-images.githubusercontent.com/10942003/96939138-c893d880-14e9-11eb-9387-003a8a22485e.png)

**Comment by cfregly** [comment]
not sure - need to investigate the EKS cluster and figure out why the nodes are not coming up.  please review EKS logs.
