### ISSUE TITLE
Error message running cell in 01_Setup_Dependencies notebook

### ISSUE THREAD

**Issue by srsaito** [data-science-on-aws/workshop#137]
I was trying out the 01_Setup_Dependencies notebook from the workshop. I’ve run this months before with no issues, but this came up today. Perhaps something has changed in underlying Python, so wanted to let you know. 
![Error message](https://raw.githubusercontent.com/srsaito/hello-world/master/error%20message.png)

**Comment by cfregly** [comment]
@srsaito Did the rest of that notebook still work?  We run those notebooks all the time and everything still seems to work.  Trying to figure out if this is truly a fatal error or just a scary non-fatal error message.  Either way, we will address.

**Comment by srsaito** [comment]
Yep, the rest of the notebook ran without a problem.

Chris Fregly <notifications@github.com>于2020年12月28日 周一下午1:36写道：

**Comment by cfregly** [comment]
added `--disable-pip-version-check`
