### ISSUE TITLE
Add seaborn to setup dependencies

### ISSUE THREAD

**Issue by ehsanmok** [data-science-on-aws/workshop#149]
Running `00_quickstart/06_Visualize_Reviews_Dataset.ipynb` fails. Here's the snapshot

![image](https://user-images.githubusercontent.com/6980212/107560075-c38a9000-6b91-11eb-86bc-12131037ff2d.png)

**Comment by cfregly** [comment]
@ehsanmok which kernel are you using?

**Comment by ehsanmok** [comment]
I chose a random tensorflow 2.3 kernel. Didn't remember saw anywhere which kernel to choose.

**Comment by cfregly** [comment]
update 00_quickstart and 01_setup
