### ISSUE TITLE
Cleanup fails for quickstart

### ISSUE THREAD

**Issue by ehsanmok** [data-science-on-aws/workshop#152]
There's no cell to %store `pipeline_endpoint_name` in the `00_quickstart/12_Register_Deploy_Model.ipynb` so the cleanup fails.

![image](https://user-images.githubusercontent.com/6980212/107587534-c9df3300-6bb6-11eb-801d-5c5eacbe868b.png)

**Comment by cfregly** [comment]
fixed.
