### ISSUE TITLE
Follow a consistent python code style

### ISSUE THREAD

**Issue by ehsanmok** [data-science-on-aws/workshop#157]
Thanks for the great materials!

I think, following a consistent style "camelCase" vs. "snake_case" is important from the eye of the viewer and generally speaks to good code. Currently there're codes with both style. I'd suggest picking one and stick with it.

**Comment by cfregly** [comment]
merged

**Comment by ehsanmok** [comment]
Thanks but I don't think there's a PR addressing this one. For example [this](https://github.com/data-science-on-aws/workshop/blob/master/02_usecases/02_Object_Detection.ipynb) is inconsistent with [this](https://github.com/data-science-on-aws/workshop/blob/master/00_quickstart/02_Copy_TSV_To_S3.ipynb).
