### ISSUE TITLE
no stored variable or alias comprehend_endpoint_arn

### ISSUE THREAD

**Issue by hanyun2019** [data-science-on-aws/workshop#18]
https://github.com/data-science-on-aws/workshop/tree/master/03_augmented

When I went through the https://github.com/data-science-on-aws/workshop/blob/master/03_augmented/02_Fix_Poor_Predictions_From_Comprehend_Custom_Text_Classifier.ipynb:

Retrieve the comprehend_endpoint_arn Deployed Previously

%store -r comprehend_endpoint_arn
**no stored variable or alias comprehend_endpoint_arn**

print(comprehend_endpoint_arn)
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-8-e792194e0848> in <module>
----> 1 print(comprehend_endpoint_arn)

NameError: name 'comprehend_endpoint_arn' is not defined

**Comment by cfregly** [comment]
Please run the 02_automl/  notebooks fully before running 03_augmented/

@antje let’s put a programmatic safeguard wait() around this code in 03_augmented/

Thanks for finding this @hanyun2019 !  We will fix soon.

**Comment by hanyun2019** [comment]
> Please run the 02_automl/ notebooks fully before running 03_augmented/
> 
> @antje let’s put a programmatic safeguard wait() around this code in 03_augmented/
> 
> Thanks for finding this @hanyun2019 ! We will fix soon.

Thanks~
