### ISSUE TITLE
Add explicit step to choose BERT’s max_seq_length from the distribution of review word counts

### ISSUE THREAD

**Issue by cfregly** [data-science-on-aws/workshop#19]

**Comment by cfregly** [comment]
1) create a notebook that queries Athena (PyAthena or AWS Data Wrangler) to calculate the distribution of word counts for all of the reviews.  

2) plot the distribution (ie. histogram with buckets) 

3) choose a threshold based on this distribution (ie. 75%)

4) choose the word count that represents all of the data below the chosen threshold

5) choose the nearest binary number (128, 256, 512) near the chosen word count.  This is the `max_seq_length`

**Comment by cfregly** [comment]
Create an Athena/PrestoDB UDF that uses BERT Tokenizer to generate the tokens from the raw text.  Then count the tokens (versus raw text)

**Comment by cfregly** [comment]
Here is a link to creating Athena UDFs:  https://aws.amazon.com/about-aws/whats-new/2019/11/amazon-athena-adds-support-for-user-defined-functions-udf/

**Comment by antje** [comment]
Here's an example of how to setup Huggingface in AWS Lambda. 
https://towardsdatascience.com/serverless-bert-with-huggingface-and-aws-lambda-625193c6cc04

We are not looking at the model serving part, but on how to use the tokenizer with AWS Lambda to implement an Athena UDF.
