### ISSUE TITLE
Unable to retrieve domainId in notebook metadata

### ISSUE THREAD

**Issue by AditAg** [data-science-on-aws/workshop#197]
Hi!

I'm facing an issue when trying to run the notebook 02_Check_Environment.ipynb in 01_Setup.ipynb. It is trying to retrieve the domainId from the notebook info, however based on following: https://docs.aws.amazon.com/sagemaker/latest/dg/nbi-metadata.html
The DomainId doesn't seem to be present in the resource_metadata.json file.

Kindly help resolve this issue.

**Comment by cfregly** [comment]
Are you using SageMaker Studio?  Or classic SageMaker Notebooks?

**Comment by cfregly** [comment]
Can you try SM Studio?

**Comment by AditAg** [comment]
I was trying this using SageMaker notebooks. Is there a fix for classic SageMaker notebooks or should I follow the course in SageMaker studio?

**Comment by cfregly** [comment]
@AditAg yes, we'd prefer if you migrated to the newer SM Studio.  Thanks!
