### ISSUE TITLE
(ResourceLimitExceeded) when calling the CreateTrainingJob operation

### ISSUE THREAD

**Issue by alanzablocki** [data-science-on-aws/workshop#200]
When trying to run the training job in 07_train, 02_Train_Reviews_BERT_Transformers_TensorFlow_ScriptMode.ipynb I get the resource error:

ResourceLimitExceeded: An error occurred (ResourceLimitExceeded) when calling the CreateTrainingJob operation: The account-level service limit 'Number of instances across all processing jobs' is 4 Instances, with current utilization of 0 Instances and a request delta of 11 Instances. Please contact AWS support to request an increase for this limit.

Any way to avoid this without contacting AWS? Changing instance type? 
Could this be because of the free tier setup? I know we did not see this error in the workshop.

I am not sure where the request for 11 instances is made, these are the settings in the notebook:

train_instance_count = 1
train_instance_type = "ml.c5.9xlarge"

Thanks,A

**Comment by cfregly** [comment]
ah, yes - we had enabled a bunch of debugging and profiling rules which require more processing jobs.

i've committed a new version here:  https://github.com/data-science-on-aws/workshop/blob/f276f0b7caadf89a0b01d38f555f32d4d32818b7/07_train/02_Train_Reviews_BERT_Transformers_TensorFlow_ScriptMode.ipynb which has these dialed down.

give it another try and re-open if it's still an issue.
