### ISSUE TITLE
Unable to create more than 10 policies.

### ISSUE THREAD

**Issue by victen18** [data-science-on-aws/workshop#219]
workshop/01_oreilly_book/04_Update_IAM_Roles_And_Policies.ipynb - 

role = iam.get_role(RoleName=role_name)
post_policies = iam.list_attached_role_policies(RoleName=role_name)["AttachedPolicies"]

required_policies = [
    "AdministratorAccess",
    "SecretsManagerReadWrite",
    "IAMFullAccess",
    "AmazonS3FullAccess",
    "AmazonAthenaFullAccess",
    "ComprehendFullAccess",
    "AmazonEC2ContainerRegistryFullAccess",
    "AmazonRedshiftFullAccess",
    "AWSStepFunctionsFullAccess",
    "AmazonSageMakerFullAccess",
    "AmazonKinesisFullAccess",
    "AmazonKinesisFirehoseFullAccess",
    "AmazonKinesisAnalyticsFullAccess",
]

admin = False

for post_policy in post_policies:
    if post_policy["PolicyName"] == "AdministratorAccess":
        admin = True
        try:
            required_policies.remove(post_policy["PolicyName"])
        except:
            break
    else:
        try:
            required_policies.remove(post_policy["PolicyName"])
        except:
            pass

if not admin and len(required_policies) > 0:
    print("*************** [ERROR] RE-RUN THIS NOTEBOOK *****************")
    for required_policy in required_policies:
        print("Not Attached: {}".format(required_policy))
else:
    setup_iam_roles_passed = True
    print("[OK] You are all set up to continue with this workshop!")

o/p:
*************** [ERROR] RE-RUN THIS NOTEBOOK *****************
Not Attached: AdministratorAccess
Not Attached: SecretsManagerReadWrite
Not Attached: ComprehendFullAccess
Not Attached: AmazonEC2ContainerRegistryFullAccess
Not Attached: AmazonRedshiftFullAccess
Not Attached: AmazonKinesisAnalyticsFullAccess

No matter how many times we run the notebook the message persists.

**Comment by cfregly** [comment]
for now, you can get rid of the last 3 kinesis roles to reduce to 10 - and try that.

let me know!  we'll look into this, as well.
