### ISSUE TITLE
Clear explanation and pointers which repository is for what purpose

### ISSUE THREAD

**Issue by oonisim** [data-science-on-aws/workshop#247]
The Data Science on AWS book says download from https://github.com/data-science-on-aws, but apparently the github structure has changed. 

Please explain what is https://github.com/data-science-on-aws/data-science-on-aws repository for as apparently it is not for the book.

**Comment by cfregly** [comment]
Book branch:  https://github.com/data-science-on-aws/data-science-on-aws/tree/oreilly-book

**Comment by cfregly** [comment]
set the default branch to the book
