### ISSUE TITLE
No access to amazon-reviews-pds

### ISSUE THREAD

**Issue by clhm** [data-science-on-aws/workshop#249]
In `data-science-on-aws/03_automl/01_Prepare_Dataset_Autopilot.ipynb`
I am unable to access the customer reviews data set. Clicking the link at the top produces this:
```
This XML file does not appear to have any style information associated with it. The document tree is shown below.
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>QRXT02TA3FDC5GSK</RequestId>
<HostId>nxtkdIXXwvCLIZnwGOvaWF2cAA21pSWr6mb1ZmbCKUf37c4kwhFo5Sdfk58Ybaln+gARNpNm1Zg=</HostId>
</Error>
```
And the aws s3 command fails:
```
!aws s3 cp 's3://amazon-reviews-pds/tsv/amazon_reviews_us_Digital_Software_v1_00.tsv.gz' ./data/
fatal error: An error occurred (403) when calling the HeadObject operation: Forbidden
```

**Comment by saxenam06** [comment]
Hi, thanks for the great work. I get the same error. Is there still a way to continue using the notebooks after the workshop as i logged in to the AWS account with the root user and not IAM user. I did even Attached policies as recommended while setting up the domain. 03_Update_IAM_Roles_And_Policies.ipynb fails at post_policies = iam.list_attach ...

**Comment by cfregly** [comment]
Change s3://amazon-reviews-pds/ => s3://dsoaws/

**Comment by saxenam06** [comment]
Thanks for your help. Somehow another category was working as below. In addition I had to change the permissions for S3 bucket in Policies. Would a different category ("Video") as below affect my progress later in this workshop? 
!aws s3 --no-sign-request cp s3://dsoaws/tsv/amazon_reviews_us_Digital_Video_Download_v1_00.tsv.gz ./data/

**Comment by clhm** [comment]
How about https://s3.amazonaws.com/amazon-reviews-pds/readme.html ?

**Comment by TheCuriousCurator** [comment]
> Thanks for your help. Somehow another category was working as below. In addition I had to change the permissions for S3 bucket in Policies. Would a different category ("Video") as below affect my progress later in this workshop? !aws s3 --no-sign-request cp s3://dsoaws/tsv/amazon_reviews_us_Digital_Video_Download_v1_00.tsv.gz ./data/

Its not working for me.
