### ISSUE TITLE
Try dataset.shuffle(`seed=None`) instead of `seed=42` in training job

### ISSUE THREAD

**Issue by cfregly** [data-science-on-aws/workshop#38]

**Comment by kvoss** [comment]
I suspect we can close this issue. I started working on patch and noticed line `dataset = dataset.repeat(epochs * steps_per_epoch)` that seems to be validating logic of using a constant for the seed value.

During the webinar, I was under the impression that `file_based_input_dataset_builder` was executed in a loop, but I don't see any indication of that in `data-science-on-aws/workshop/blob/master/07_train/01_Train_Reviews_BERT_Transformers_TensorFlow_AdHoc.ipynb`.
