### ISSUE TITLE
More ML services to include in workshop?

### ISSUE THREAD

**Issue by keypointt** [data-science-on-aws/workshop#5]
Hi Antje and Chris, thanks a lot for this great workshop, very helpful!

Just a minor question that any plan to include more AWS products?
Like AWS Chatbot, Amazon Lex, Polly, Rekognition, Transcribe, Elastic Inference, Textract, Personalize, AmazonForecast, etc.

Thanks again for the workshop!

**Comment by cfregly** [comment]
We have elastic inference example, but we don't yet have examples of the rest at this time.  

There are many more examples, however, in the AWS Samples github repo:  https://github.com/aws-samples/
