### ISSUE TITLE
Typo in instructions: New > Terminal

### ISSUE THREAD

**Issue by MarrickLip** [data-science-on-aws/workshop#7]
<img width="746" alt="Screen Shot 2020-07-21 at 4 52 43 PM" src="https://user-images.githubusercontent.com/24652534/88014248-9a150300-cb72-11ea-882a-9620a32bf892.png">

@cfregly you said to make a note of this during the workshop (loving it btw)

**Comment by cfregly** [comment]
fixed.  and also updated the image with more arrows to highlight the scroll down.
