### ISSUE TITLE
Wrong version of Data Wrangler from pip install

### ISSUE THREAD

**Issue by ChubaOraka** [data-science-on-aws/workshop#72]
With reference to the [04_ingest/05_Query_Data_With_AWS_DataWrangler.ipynb](https://github.com/data-science-on-aws/workshop/blob/87ab673be73520aef2fb35df8665da120e0b76ba/04_ingest/05_Query_Data_With_AWS_DataWrangler.ipynb) notebook:
The `pip install -q awswrangler==1.2.0` command has the wrong version number according the [AWS Data Wrangler Github issues page](https://github.com/awslabs/aws-data-wrangler/issues/357). Please update to 1.7.0 or higher.

**Comment by cfregly** [comment]
this will be fixed with #72

**Comment by ChubaOraka** [comment]
I noticed that the notebook `01_setup/01_Setup_Dependencies.ipynb` is supposed to have installed all the dependencies. But for some weird reason, I got errors on my first run of some subsequent notebooks before uncommenting the `pip install ...` lines. It might be an issue with the SageMaker instance. 🤷
