### ISSUE TITLE
Remove [0:512] on predictions

### ISSUE THREAD

**Issue by cfregly** [data-science-on-aws/workshop#78]
![image](https://user-images.githubusercontent.com/1438064/93690390-9b887c00-fa8c-11ea-8a51-b1313aaa134a.png)

**Comment by antje** [comment]
Check if that is the same issue:

https://github.com/huggingface/transformers/issues/4224  
https://github.com/huggingface/transformers/pull/3857/files

**Comment by cfregly** [comment]
this was caused by upgrading to transformers 3.x
