### ISSUE TITLE
workshop/03_augmented/00_Overview.ipynb does not work, invalid json

### ISSUE THREAD

**Issue by jtrollin** [data-science-on-aws/workshop#8]
when trying to load in Jupiter it gives an error about invalid json and the file will not load in the github unless I chose raw format, then you can see at the bottom of the file that it is invalid json.

Looks like the following needs to be removed from the bottom of the file.

`}
  "kernelspec": {
   "display_name": "conda_python3",
   "language": "python",
   "name": "conda_python3"
  },`

**Comment by cfregly** [comment]
thanks!
