### ISSUE TITLE
Unable to locate credentials

### ISSUE THREAD

**Issue by cfregly** [data-science-on-aws/workshop#89]
![image](https://user-images.githubusercontent.com/1438064/93956459-207eca00-fd07-11ea-838e-663608ba6aaf.png)

**Comment by cfregly** [comment]
note:  after kernel restart and re-run, i don't see it.  i see "Role already exists.  This is OK."

**Comment by cfregly** [comment]
something to keep an eye on ^^

**Comment by cfregly** [comment]
I saw this is another notebook (Personalize) that might be similar:

![image](https://user-images.githubusercontent.com/1438064/94023004-8f413f00-fd6a-11ea-9708-b05747288847.png)

**Comment by cfregly** [comment]
![image](https://user-images.githubusercontent.com/1438064/94196450-37d5c880-fe69-11ea-95ad-27312c0a83f2.png)

**Comment by antje** [comment]
Not going to fix.
