### ISSUE TITLE
Fix OOM error in adhoc training

### ISSUE THREAD

**Issue by antje** [data-science-on-aws/workshop#90]
![image](https://user-images.githubusercontent.com/23338582/94036474-a6ad1600-fdc4-11ea-8faa-639ef181cb38.png)

Smaller batch size (from 1000 to 250) seems to help.

**Comment by cfregly** [comment]
lowered the values.  fixed.

**Comment by antje** [comment]
Error still showing up: 

![image](https://user-images.githubusercontent.com/23338582/96851635-85d5f000-1458-11eb-84a8-c7570672a089.png)


![image](https://user-images.githubusercontent.com/23338582/96851578-76ef3d80-1458-11eb-9a36-653149d0d8d9.png)

**Comment by antje** [comment]
Might be related to small notebook instance and many Jupyter notebooks open. Shutting down notebooks and re-running worked.
