### ISSUE TITLE
Possibly increase Maximum session duration in the role

### ISSUE THREAD

**Issue by cfregly** [data-science-on-aws/workshop#94]
![image](https://user-images.githubusercontent.com/1438064/94167544-79527d80-fe41-11ea-82aa-7c96d967f19d.png)

**Comment by cfregly** [comment]
![image](https://user-images.githubusercontent.com/1438064/94176238-a5bfc700-fe4c-11ea-94de-e76a534488a8.png)

**Comment by antje** [comment]
# Update AWS config file
!aws configure set duration_seconds 43200

# Get IAM Roles
iam_roles = iam.list_roles()['Roles']

# Update relevant roles
iam_roles_to_update = []
for iam_role in iam_roles:
    if iam_role['RoleName'].startswith('TeamRole'):
        iam_role['MaxSessionDuration'] = 43200
        print('Set role `{}` MaxSessionDuration to {}'.format(iam_role['RoleName'], iam_role['MaxSessionDuration']))
        iam_roles_to_update.append(iam_role['RoleName'])
        
    elif iam_role['RoleName'].startswith('IibsAdminAccess'):
        iam_role['MaxSessionDuration'] = 43200
        print('Set role `{}` MaxSessionDuration to {}'.format(iam_role['RoleName'], iam_role['MaxSessionDuration']))
        iam_roles_to_update.append(iam_role['RoleName'])

for i in iam_roles_to_update:
    !aws iam update-role --role-name $i --max-session-duration 43200

**Comment by antje** [comment]
Added to https://github.com/data-science-on-aws/workshop/blob/d36fe7d525d5f9b4b66fcba73a358d64dafb3aa1/01_setup/wip/Increase_Max_Console_Session_Duration.ipynb
